server:
  port: 9200

spring:

  application:
    name: SpringSecurity

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456

  redis:
    host: 121.43.158.136
    port: 6379
    password: redis85444
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: false

logging:
  level:
    com.example.SpringSecurity.mapper: debug
  config: classpath:logging/logging-log4j2.yml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
#  secret: abcdefghijklmnopqrstuvwxyz
  secret: gwe1vVoEf7wu
  # 令牌有效期（默认30分钟）
  expireTime: 30