server:
  port: 9200

spring:

  application:
    name: SpringSecurity


  security:
    user:
      name: user
      password: 123456
      roles: admin

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.158.136:3306/wxArticle?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: aaa85444

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: false

logging:
  level:
    com.example.SpringSecurity.mapper: debug
  config: classpath:logging/logging-log4j2.yml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
#  secret: abcdefghijklmnopqrstuvwxyz
  secret: gwe1vVoEf7wu
  # 令牌有效期（默认30分钟）
  expireTime: 30